# -*- coding: utf-8 -*-
"""Projeto de Linguagens de Programação.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PbOp7XLgGTZ8sGooUgwdBvgkb44ZX7M-
"""

import pandas as pd
import altair as alt

# Inicio e elaboração do código - Jaqueline
# --- Configurações Iniciais ---
DATA_PATH = '/content/cert_2010-2019.csv'

# Carregar dados
df = pd.read_csv(DATA_PATH, delimiter=';')

# Imprimir os nomes das colunas, incluindo espaços em branco
print("Nomes das colunas (incluindo espaços em branco):", df.columns)

# Verificar e corrigir coluna 'Ano' com espaços em branco
if 'Ano ' in df.columns:  # Note o espaço extra após 'Ano'
    df.rename(columns={'Ano ': 'Ano'}, inplace=True)
    print("Espaços em branco extras removidos da coluna 'Ano'.")

# Converter coluna 'Ano' para numérica
df['Ano'] = pd.to_numeric(df['Ano'], errors='coerce')

# Calcular o total de cada tipo de ataque por ano
df_ataques_por_ano = df.groupby('Ano')[['Worm', 'DOS', 'Invasao', 'Web', 'Scan', 'Fraude', 'Outros']].sum().reset_index()

# Transformar o DataFrame para o formato longo
df_ataques_por_ano_longo = df_ataques_por_ano.melt(id_vars='Ano', var_name='Tipo de Ataque', value_name='Total')

# Calcular o total geral de ataques
total_geral = df_ataques_por_ano_longo['Total'].sum()

# Adicionar a coluna de proporção
df_ataques_por_ano_longo['Proporção'] = (df_ataques_por_ano_longo['Total'] / total_geral) * 100

# Visualização de dados

# ajustes e apresentação dos gráfico - Hernane

# Gráfico 1: Evolução do Total de Ataques por Tipo ao Longo dos Anos
chart1 = alt.Chart(df_ataques_por_ano_longo).mark_line(point=True).encode(
    x=alt.X('Ano:N', axis=alt.Axis(title='Ano')),
    y=alt.Y('Total:Q', axis=alt.Axis(title='Total de Ataques')),
    color=alt.Color('Tipo de Ataque:N', legend=alt.Legend(title='Tipo de Ataque')),
    tooltip=['Ano', 'Tipo de Ataque', 'Total']
).interactive()

display(chart1)

# Gráfico 2: Total de Ataques por Tipo
chart2 = alt.Chart(df_ataques_por_ano_longo).mark_bar().encode(
    x=alt.X('Tipo de Ataque:N', sort='-y', axis=alt.Axis(title='Tipo de Ataque', labelAngle=-45)),
    y=alt.Y('sum(Total):Q', axis=alt.Axis(title='Total de Ataques')),
    tooltip=['Tipo de Ataque', 'sum(Total)']
).interactive()

display(chart2)

from google.colab import drive
drive.mount('/content/drive')